---
name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  size:
    name: Size Check
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Check bundle sizes
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: size

  build:
    name: Use Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    needs:
      - size
    env:
      CI: true
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: yarn install
        run: yarn
      - name: Unittesting
        run: yarn test
      - name: Linting
        if: ${{ matrix.node-version == '16.x' }}
        run: yarn lint
      - name: Coverage
        run: yarn coverage
