---
name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Lint and test
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: yarn install
        run: yarn
      - name: Unittesting
        run: yarn test
      - name: Linting
        if: ${{ matrix.node-version == '18' }}
        run: yarn lint
      - name: Coverage
        run: yarn coverage
