---
name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Lint and test
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: yarn install
        run: yarn
      - name: Unittesting
        run: yarn test
      - name: Linting
        if: ${{ matrix.node-version == '16.x' }}
        run: yarn lint
      - name: Coverage
        run: yarn coverage
