---
name: size

on:
  pull_request:
    branches:
    - main

jobs:
  size:
    name: Size Check
    runs-on: ubuntu-latest
    env:
      CI: true
      CI_JOB_NUMBER: 1
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Check bundle sizes
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: size
